# Generated by Django 5.1.6 on 2025-02-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='certification_file',
            field=models.FileField(blank=True, null=True, upload_to='certifications/'),
        ),
    ]
