# Generated by Django 5.1.6 on 2025-03-04 01:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_experience_certification_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='certification_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certifications'),
        ),
    ]
